name: reform

dependencies:
  - name: base
    version: ">= 4.7 && < 5"
    mixin:
      - hiding (Prelude)
  - name: relude
    mixin:
      - (Relude as Prelude)
  - optparse-applicative >= 0.16.1.0

library:
  source-dirs: src

executable:
  main: src/Main.hs
